services:
  - type: web
    name: snow-alert
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_ENABLED
        value: true
      - key: EMAIL_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: CHECK_HOUR
        value: 16
      - key: CHECK_MINUTE
        value: 0
      - key: SEARCH_RADIUS_METERS
        value: 200
